### ISSUE TITLE
DeepMind manipulation task and Drawer World

### ISSUE THREAD

**Issue by zichunxx** [gemcollector/PIE-G#1]
Hi! @gemcollector 

Could you please update the training script and associated tasks to include the Deepmind manipulation task and Drawer World mentioned in your paper? I'd like to reproduce the results in your paper and see how the model performs with more tasks. 

Looking forward to your reply! Thanks in advance!

**Comment by gemcollector** [comment]
Hello zichun! Sorry for the late reply! The drawer world is introduced from https://github.com/frank-xwang/VAI-ReinforcementLearning/. You can check this link to access the environment. If you want to reproduce the results, please carefully check the hyper-parameters.  The Deepmind manipulation task is modified from the original `dm-control` tasks. You should manually change the mujoco setting of each scene. It's a little bit complicated. 

Actually, I recommend you to use the https://github.com/gemcollector/RL-ViGen, and the robosuite part will match your requirements. :) If you have further questions, please let me know. :)

**Comment by zichunxx** [comment]
Thanks for your patient response, I will dive into the RL-ViGen.
